### ISSUE TITLE
Configurar y crear en DO todo lo necesario

### ISSUE THREAD

**Issue by yodra** [fullstacktf/fs5-gestiondesocios-backend#2]
-  [x] Crear un droplet
-  [x] Instalar docker
-  [x] Configuración Cloudflare para HTTPS y gestionar DNS
-  [x] Configuración Nginx/Apache como servidor
